export const globalKeywords = [
  'fotógrafo de casamento em São Paulo',
  'fotógrafo de casamento SP',
  'Ivan Dias fotógrafo',
]

export const pageKeywords: Record<string, string[]> = {
  // ── PÁGINAS FIXAS ──────────────────────────────────────────────
  home: [...globalKeywords, 'fotografia de casamento São Paulo', 'pré-wedding São Paulo', 'mini wedding São Paulo', 'fotógrafo casamento Moema', 'fotógrafo casamento autoral SP'],
  'cobertura-completa': [...globalKeywords, 'cobertura completa casamento SP', 'fotógrafo making of noiva SP', 'foto e vídeo casamento São Paulo', 'fotógrafo cerimônia e festa SP'],
  'pre-wedding': [...globalKeywords, 'ensaio pré-wedding São Paulo', 'book de noivos SP', 'ensaio externo casal São Paulo', 'pré-wedding parques SP'],
  'mini-wedding': [...globalKeywords, 'fotógrafo mini wedding São Paulo', 'casamento intimista SP', 'mini wedding até 80 convidados SP', 'fotógrafo cerimônia pequena SP'],
  drone: [...globalKeywords, 'drone casamento São Paulo', 'fotografia aérea casamento SP', 'vídeo drone casamento SP', 'fotógrafo com drone casamento'],

  // ── CIDADE / BAIRRO (39) ───────────────────────────────────────
  'fotografo-de-casamento-itaim-bibi': [...globalKeywords, 'fotógrafo casamento Itaim Bibi', 'casamento Itaim Bibi SP', 'espaços casamento Itaim Bibi', 'ensaio pré-wedding Itaim Bibi'],
  'fotografo-de-casamento-jardins': [...globalKeywords, 'fotógrafo casamento Jardins SP', 'casamento Jardim Paulista', 'buffets casamento Jardins', 'ensaio pré-wedding Jardins'],
  'fotografo-de-casamento-moema': [...globalKeywords, 'fotógrafo casamento Moema', 'casamento Moema SP', 'espaços casamento Moema', 'ensaio casal Moema'],
  'fotografo-de-casamento-pinheiros': [...globalKeywords, 'fotógrafo casamento Pinheiros SP', 'casamento Pinheiros São Paulo', 'espaços casamento Pinheiros'],
  'fotografo-de-casamento-vila-mariana': [...globalKeywords, 'fotógrafo casamento Vila Mariana', 'casamento Vila Mariana SP', 'igreja casamento Vila Mariana'],
  'fotografo-de-casamento-perdizes': [...globalKeywords, 'fotógrafo casamento Perdizes SP', 'casamento Perdizes São Paulo', 'buffets casamento Perdizes'],
  'fotografo-de-casamento-tatuape': [...globalKeywords, 'fotógrafo casamento Tatuapé', 'casamento Zona Leste SP', 'espaços casamento Tatuapé'],
  'fotografo-de-casamento-santana': [...globalKeywords, 'fotógrafo casamento Santana SP', 'casamento Zona Norte SP', 'buffets casamento Santana'],
  'fotografo-de-casamento-sorocaba': [...globalKeywords, 'fotógrafo casamento Sorocaba', 'casamento Sorocaba SP', 'Welucci Sorocaba', 'fazenda casamento Sorocaba'],
  'fotografo-de-casamento-campinas': [...globalKeywords, 'fotógrafo casamento Campinas', 'casamento Campinas SP', 'buffets casamento Campinas'],
  'fotografo-de-casamento-santos': [...globalKeywords, 'fotógrafo casamento Santos', 'casamento litoral Santos SP', 'ensaio pré-wedding Santos'],
  'fotografo-de-casamento-guarulhos': [...globalKeywords, 'fotógrafo casamento Guarulhos', 'casamento Guarulhos SP', 'buffets casamento Guarulhos'],
  'fotografo-de-casamento-santo-andre': [...globalKeywords, 'fotógrafo casamento Santo André', 'casamento ABC paulista', 'espaços casamento Santo André', 'fotógrafo casamento ABCD'],
  'fotografo-de-casamento-barueri': [...globalKeywords, 'fotógrafo casamento Barueri', 'casamento Alphaville SP', 'espaços casamento Tamboré'],
  'fotografo-de-casamento-mogi-das-cruzes': [...globalKeywords, 'fotógrafo casamento Mogi das Cruzes', 'casamento Alto Tietê', 'fazenda casamento Mogi'],
  'fotografo-de-casamento-osasco': [...globalKeywords, 'fotógrafo casamento Osasco', 'casamento Osasco SP', 'buffets casamento Osasco'],
  'fotografo-de-casamento-guaruja': [...globalKeywords, 'fotógrafo casamento Guarujá', 'casamento praia Guarujá', 'destination wedding Guarujá'],
  'fotografo-de-casamento-jundiai': [...globalKeywords, 'fotógrafo casamento Jundiaí', 'casamento vinícola Jundiaí', 'casamento Vinhedo SP'],
  'fotografo-de-casamento-suzano': [...globalKeywords, 'fotógrafo casamento Suzano', 'casamento Alto Tietê Suzano', 'espaços casamento Suzano'],
  'fotografo-de-casamento-tatui': [...globalKeywords, 'fotógrafo casamento Tatuí', 'casamento interior Tatuí SP', 'espaços casamento Tatuí'],
  'fotografo-de-casamento-atibaia': [...globalKeywords, 'fotógrafo casamento Atibaia', 'casamento serra Atibaia SP', 'chácara casamento Atibaia'],
  'fotografo-de-casamento-cotia': [...globalKeywords, 'fotógrafo casamento Cotia', 'casamento Cotia SP', 'espaços casamento Granja Viana'],
  'fotografo-de-casamento-indaiatuba': [...globalKeywords, 'fotógrafo casamento Indaiatuba', 'casamento interior Indaiatuba', 'espaços casamento Indaiatuba'],
  'fotografo-de-casamento-itu': [...globalKeywords, 'fotógrafo casamento Itu', 'casamento fazenda Itu SP', 'espaços casamento Itu'],
  'fotografo-de-casamento-ilhabela': [...globalKeywords, 'fotógrafo casamento Ilhabela', 'destination wedding Ilhabela', 'casamento praia Ilhabela'],
  'fotografo-de-casamento-piracicaba': [...globalKeywords, 'fotógrafo casamento Piracicaba', 'casamento interior Piracicaba', 'espaços casamento Piracicaba'],
  'fotografo-de-casamento-sao-bernardo-do-campo': [...globalKeywords, 'fotógrafo casamento São Bernardo', 'casamento SBC', 'espaços casamento São Bernardo do Campo'],
  'fotografo-de-casamento-trancoso': [...globalKeywords, 'fotógrafo casamento Trancoso', 'destination wedding Trancoso', 'casamento Bahia Trancoso'],
  'fotografo-de-casamento-ubatuba': [...globalKeywords, 'fotógrafo casamento Ubatuba', 'casamento praia Ubatuba SP', 'ensaio pré-wedding Ubatuba'],
  'fotografo-de-casamento-sao-jose-dos-campos': [...globalKeywords, 'fotógrafo casamento São José dos Campos', 'casamento Vale do Paraíba', 'espaços casamento SJC'],
  'fotografo-de-casamento-mairipora': [...globalKeywords, 'fotógrafo casamento Mairiporã', 'casamento Serra da Cantareira', 'chácara casamento Mairiporã'],
  'fotografo-de-casamento-vila-olimpia': [...globalKeywords, 'fotógrafo casamento Vila Olímpia', 'casamento Vila Olímpia SP', 'espaços casamento Vila Olímpia'],
  'fotografo-de-casamento-brooklin': [...globalKeywords, 'fotógrafo casamento Brooklin SP', 'casamento Brooklin São Paulo', 'espaços casamento Brooklin'],
  'fotografo-de-casamento-diadema': [...globalKeywords, 'fotógrafo casamento Diadema', 'casamento ABCDM Diadema', 'espaços casamento Diadema'],
  'fotografo-de-casamento-maua': [...globalKeywords, 'fotógrafo casamento Mauá', 'casamento Grande ABC Mauá', 'espaços casamento Mauá'],
  'fotografo-de-casamento-morumbi': [...globalKeywords, 'fotógrafo casamento Morumbi', 'casamento Morumbi SP', 'Casa Welucci Morumbi'],
  'fotografo-de-casamento-intimista': [...globalKeywords, 'fotógrafo casamento intimista SP', 'casamento intimista São Paulo', 'fotografia casamento poucos convidados'],
  'fotografo-de-casamento-perto-de-mim': [...globalKeywords, 'fotógrafo casamento perto de mim', 'fotógrafo casamento próximo SP', 'contratar fotógrafo casamento SP'],
  'fotografo-de-casamento-ribeirao-pires': [...globalKeywords, 'fotógrafo casamento Ribeirão Pires', 'casamento Ribeirão Pires SP', 'chácara casamento Ribeirão Pires'],

  // ── ESPAÇO / BUFFET (34) ───────────────────────────────────────
  'fotografo-casamento-espaco-win-santo-andre': [...globalKeywords, 'Espaço Win Santo André', 'casamento Espaço Win', 'buffet casamento Santo André'],
  'fotografo-casamento-mezzatorre-eventos': [...globalKeywords, 'Mezzatorre Eventos Santo André', 'casamento Mezzatorre', 'buffet casamento ABC'],
  'fotografo-casamento-espaco-figueiras': [...globalKeywords, 'Espaço Figueiras Santo André', 'casamento Figueiras', 'espaço eventos Santo André'],
  'fotografo-casamento-casa-laranjeira-maztiga': [...globalKeywords, 'Casa Laranjeira Maztiga', 'casamento Casa Laranjeira Santo André', 'buffet Maztiga'],
  'fotografo-casamento-espaco-alfarre': [...globalKeywords, 'Espaço Alfarre Santo André', 'casamento Alfarre', 'espaço eventos ABC'],
  'fotografo-casamento-buffet-status': [...globalKeywords, 'Buffet Status Santo André', 'casamento Buffet Status', 'buffet casamento Santo André'],
  'fotografo-casamento-esplannada-santo-andre': [...globalKeywords, 'Esplannada Santo André', 'casamento Esplannada', 'espaço eventos Santo André'],
  'fotografo-casamento-grande-ville': [...globalKeywords, 'Grande Ville Santo André', 'casamento Grande Ville', 'buffet Grande Ville ABC'],
  'fotografo-casamento-espaco-monaco': [...globalKeywords, 'Espaço Mônaco Santo André', 'mini wedding Espaço Mônaco', 'casamento intimista Santo André'],
  'fotografo-casamento-buffet-dmatos': [...globalKeywords, 'Buffet D\'Matos Santo André', 'casamento D\'Matos', 'buffet eventos ABC'],
  'fotografo-casamento-espaco-pallazium': [...globalKeywords, 'Espaço Pallazium Santo André', 'casamento Pallazium', 'espaço eventos Santo André'],
  'fotografo-casamento-hotel-plaza-mayor': [...globalKeywords, 'Hotel Plaza Mayor Santo André', 'casamento Hotel Plaza Mayor', 'hotel casamento ABC'],
  'fotografo-casamento-espaco-favoritto': [...globalKeywords, 'Espaço Favoritto São Bernardo', 'casamento Espaço Favoritto SBC', 'buffet casamento SBC'],
  'fotografo-casamento-sitio-sao-jorge-sbc': [...globalKeywords, 'Sítio São Jorge São Bernardo', 'casamento Sítio São Jorge', 'sítio casamento SBC'],
  'fotografo-casamento-recanto-dos-sonhos-sbc': [...globalKeywords, 'Recanto dos Sonhos São Bernardo', 'casamento Recanto dos Sonhos', 'espaço casamento SBC'],
  'fotografo-casamento-lago-park-sao-bernardo': [...globalKeywords, 'Lago Park São Bernardo', 'casamento Lago Park SBC', 'buffet casamento SBC'],
  'fotografo-casamento-espelho-dagua-sbc': [...globalKeywords, 'Espelho D\'Água São Bernardo', 'casamento Espelho D\'Água', 'espaço eventos SBC'],
  'fotografo-casamento-allegro-buffet-sbc': [...globalKeywords, 'Allegro Buffet São Bernardo', 'casamento Allegro Buffet', 'buffet casamento SBC'],
  'fotografo-casamento-pbsom-eventos': [...globalKeywords, 'PBsom Eventos São Bernardo', 'casamento PBsom', 'espaço eventos SBC'],
  'fotografo-casamento-buffet-7-mares': [...globalKeywords, 'Buffet 7 Mares São Caetano', 'casamento Buffet 7 Mares', 'buffet casamento São Caetano'],
  'fotografo-casamento-cook-hall-buffet': [...globalKeywords, 'Cook Hall Buffet São Caetano', 'casamento Cook Hall', 'buffet casamento SCS'],
  'fotografo-casamento-alameda-7-sao-caetano': [...globalKeywords, 'Alameda 7 São Caetano', 'mini wedding Alameda 7', 'casamento intimista SCS'],
  'fotografo-casamento-casa-flora-eventos': [...globalKeywords, 'Casa Flora Eventos São Caetano', 'casamento Casa Flora', 'espaço eventos SCS'],
  'fotografo-casamento-eco-buffet-social': [...globalKeywords, 'Eco Buffet Social São Caetano', 'casamento Eco Buffet', 'buffet sustentável SCS'],
  'fotografo-casamento-estacao-840': [...globalKeywords, 'Estação 840 Osasco', 'casamento Estação 840', 'casamento industrial chic Osasco'],
  'fotografo-casamento-maison-bella-vista-osasco': [...globalKeywords, 'Maison Bella Vista Osasco', 'casamento Maison Bella Vista', 'espaço casamento Osasco'],
  'fotografo-casamento-spazio-valentina-osasco': [...globalKeywords, 'Spazio Valentina Osasco', 'casamento Spazio Valentina', 'espaço eventos Osasco'],
  'fotografo-casamento-espaco-catedral-osasco': [...globalKeywords, 'Espaço Catedral Osasco', 'casamento Espaço Catedral', 'espaço eventos Osasco'],
  'fotografo-casamento-buffet-madeira-alphaville': [...globalKeywords, 'Buffet Madeira Alphaville', 'casamento Buffet Madeira', 'buffet casamento Alphaville'],
  'fotografo-casamento-ravena-garden': [...globalKeywords, 'Ravena Garden Mairiporã', 'casamento Ravena Garden', 'espaço casamento Cantareira'],
  'fotografo-casamento-sitio-florentino-mairipora': [...globalKeywords, 'Sítio Florentino Mairiporã', 'destination wedding Mairiporã', 'sítio casamento Cantareira'],
  'fotografo-casamento-quinta-da-cantareira': [...globalKeywords, 'Quinta da Cantareira Mairiporã', 'casamento Quinta da Cantareira', 'espaço serra casamento SP'],
  'fotografo-casamento-villa-vezzane-mairipora': [...globalKeywords, 'Villa Vezzane Mairiporã', 'casamento Villa Vezzane', 'espaço casamento serra SP'],
  'fotografo-casamento-mon-chale-mairipora': [...globalKeywords, 'Mon Chalé Mairiporã', 'casamento Mon Chalé', 'chalé casamento Cantareira'],
  'fotografo-casamento-casa-por-do-sol-cantareira': [...globalKeywords, 'Casa Pôr do Sol Cantareira', 'mini wedding Cantareira', 'casamento pôr do sol serra SP'],
  'fotografo-casamento-estancia-silvestre-ribeirao-pires': [...globalKeywords, 'Estância Silvestre Ribeirão Pires', 'casamento Estância Silvestre', 'espaço rural casamento ABC'],
  'fotografo-casamento-chacara-flores-ribeirao-pires': [...globalKeywords, 'Chácara Flores Ribeirão Pires', 'casamento Chácara Flores', 'chácara casamento ABC'],
  'fotografo-casamento-espaco-vista-verde-ribeirao-pires': [...globalKeywords, 'Espaço Vista Verde Ribeirão Pires', 'casamento Vista Verde', 'espaço casamento serra ABC'],
  'fotografo-casamento-villa-castanieri-mogi': [...globalKeywords, 'Villa Castanieri Mogi das Cruzes', 'casamento Villa Castanieri', 'espaço italiano casamento Mogi'],
  'fotografo-casamento-casarao-la-villa-mogi': [...globalKeywords, 'Casarão La Villa Mogi das Cruzes', 'casamento fazenda Mogi', 'casamento rústico Mogi'],

  // ── WELUCCI (14) ───────────────────────────────────────────────
  'fotografo-casamento-welucci-estaiada': [...globalKeywords, 'Welucci Estaiada', 'casamento Ponte Estaiada SP', 'espaço casamento vista Estaiada'],
  'fotografo-casamento-welucci-single': [...globalKeywords, 'Welucci Single Moema', 'casamento Welucci Single', 'espaço casamento Moema SP'],
  'fotografo-casamento-welucci-sansu': [...globalKeywords, 'Welucci Sansu Araçoiaba da Serra', 'casamento zen japonês SP', 'espaço casamento Sorocaba'],
  'fotografo-casamento-welucci-fontana': [...globalKeywords, 'Welucci Fontana Votorantim', 'casamento vila italiana SP', 'espaço casamento fontes água'],
  'fotografo-casamento-welucci-kratos': [...globalKeywords, 'Welucci Kratos Vinhedo', 'casamento Welucci Kratos', 'espaço casamento Campinas Jundiaí'],
  'fotografo-casamento-casa-welucci': [...globalKeywords, 'Casa Welucci Morumbi', 'casamento Casa Welucci', 'espaço casamento intimista Morumbi'],
  'fotografo-casamento-welucci-gardens': [...globalKeywords, 'Welucci Gardens São Paulo', 'casamento jardins Welucci', 'espaço casamento verde SP'],
  'fotografo-casamento-welucci-village': [...globalKeywords, 'Welucci Village São Paulo', 'casamento Welucci Village', 'espaço casamento teto vidro SP'],
  'fotografo-casamento-welucci-the-one': [...globalKeywords, 'Welucci The One São Paulo', 'casamento alto padrão Welucci', 'espaço exclusivo casamento SP'],
  'fotografo-casamento-welucci-vila-real': [...globalKeywords, 'Welucci Vila Real', 'casamento campo perto SP', 'espaço casamento europeu SP'],
  'fotografo-casamento-welucci-fagundes': [...globalKeywords, 'Welucci Fagundes', 'casamento casarão colonial SP', 'espaço casamento lago SP'],
  'fotografo-casamento-welucci-ocean': [...globalKeywords, 'Welucci Ocean', 'casamento praia Welucci', 'espaço casamento litoral SP'],
  'fotografo-casamento-welucci-canto-verde': [...globalKeywords, 'Welucci Canto Verde', 'casamento Serra da Mantiqueira', 'espaço casamento serra SP'],
  'fotografo-casamento-grupo-welucci': [...globalKeywords, 'Grupo Welucci casamento', 'espaços Grupo Welucci SP', '13 unidades Welucci'],

  // ── QUINTAL (7) ────────────────────────────────────────────────
  'fotografo-casamento-espaco-quintal': [...globalKeywords, 'Espaço Quintal casamento', 'Rustic Wedding São Paulo', 'casamento rústico patrimônio tombado'],
  'fotografo-casamento-casa-quintal': [...globalKeywords, 'Casa Quintal casamento', 'Comfort Wedding São Paulo', 'casamento residencial SP'],
  'fotografo-casamento-casinha-quintal': [...globalKeywords, 'Casinha Quintal mini wedding', 'Mini Wedding francês SP', 'casamento intimista Quintal'],
  'fotografo-casamento-celeiro-quintal': [...globalKeywords, 'Celeiro Quintal casamento', 'Farm Wedding São Paulo', 'casamento celeiro SP'],
  'fotografo-casamento-chale-quintal': [...globalKeywords, 'Chalé Quintal casamento', 'Romantic Wedding São Paulo', 'casamento romântico SP'],
  'fotografo-casamento-botanico-quintal': [...globalKeywords, 'Botânico Quintal casamento', 'Fresh Wedding São Paulo', 'casamento jardim botânico SP'],
  'fotografo-casamento-grupo-quintal': [...globalKeywords, 'Grupo Quintal casamento', 'espaços Grupo Quintal SP', 'casamento conceitual São Paulo'],

  // ── IGREJAS (10) ───────────────────────────────────────────────
  'fotografo-casamento-igreja-nossa-senhora-do-brasil': [...globalKeywords, 'casamento Nossa Senhora do Brasil', 'igreja casamento Jardim América', 'regras casamento NSB SP'],
  'fotografo-casamento-igreja-sao-jose-jardim-europa': [...globalKeywords, 'casamento São José Jardim Europa', 'igreja casamento Jardins SP', 'nave estreita fotografia igreja'],
  'fotografo-casamento-catedral-anglicana-sao-paulo': [...globalKeywords, 'casamento Catedral Anglicana SP', 'casamento ecumênico São Paulo', 'igreja casamento diverso SP'],
  'fotografo-casamento-catedral-do-carmo-santo-andre': [...globalKeywords, 'Catedral do Carmo Santo André', 'casamento catedral ABC', 'igreja casamento Santo André'],
  'fotografo-casamento-matriz-sagrada-familia-sao-caetano': [...globalKeywords, 'Matriz Sagrada Família São Caetano', 'casamento Matriz SCS', 'igreja casamento São Caetano'],
  'fotografo-casamento-matriz-sao-bernardo': [...globalKeywords, 'Matriz São Bernardo casamento', 'Paróquia Boa Viagem SBC', 'igreja casamento SBC'],
  'fotografo-casamento-nossa-senhora-de-lourdes-alphaville': [...globalKeywords, 'Nossa Senhora de Lourdes Alphaville', 'casamento igreja Barueri', 'limite padrinhos igreja SP'],
  'fotografo-casamento-capela-sao-francisco-de-assis': [...globalKeywords, 'Capela São Francisco de Assis SP', 'mini wedding capela SP', 'casamento rústico capela Osasco'],
  'fotografo-casamento-igreja-sao-benedito-mogi': [...globalKeywords, 'Igreja São Benedito Mogi', 'casamento patrimônio histórico Mogi', 'igreja colonial casamento SP'],

  // ── HUBS POR TIPO (4) ─────────────────────────────────────────
  'casamento-no-campo-perto-de-sao-paulo': [...globalKeywords, 'casamento no campo perto de SP', 'casamento ao ar livre São Paulo', 'chácara casamento SP', 'espaços campo casamento'],
  'casamento-no-litoral-perto-de-sao-paulo': [...globalKeywords, 'casamento no litoral SP', 'casamento praia São Paulo', 'destination wedding litoral SP'],
  'casamento-na-cidade-sao-paulo': [...globalKeywords, 'casamento na cidade SP', 'buffets casamento São Paulo', 'espaços urbanos casamento SP'],
  'casamento-no-interior-de-sao-paulo': [...globalKeywords, 'casamento interior São Paulo', 'casamento Campinas Jundiaí Sorocaba', 'fotógrafo casamento interior SP'],

  // ── PREÇO (8) ──────────────────────────────────────────────────
  'quanto-custa-fotografo-casamento-sao-paulo': [...globalKeywords, 'quanto custa fotógrafo casamento SP', 'preço fotógrafo casamento São Paulo', 'pacote fotografia casamento SP'],
  'quanto-custa-fotografo-casamento-2-horas': [...globalKeywords, 'fotógrafo casamento 2 horas preço', 'cobertura curta casamento SP', 'pacote fotografia civil SP'],
  'quanto-custa-book-20-fotos-casamento': [...globalKeywords, 'book 20 fotos casamento preço', 'pacote fotos casamento reduzido', 'fotógrafo casamento pacote básico'],
  'como-negociar-preco-fotografo-casamento': [...globalKeywords, 'negociar preço fotógrafo casamento', 'desconto fotógrafo casamento', 'orçamento fotografia casamento'],
  'quanto-custa-fotografo-casamento-sp-precos': [...globalKeywords, 'preços fotógrafo casamento SP 2026', 'tabela preço fotógrafo casamento', 'pacotes fotografia casamento SP'],
  'bodas-de-ouro-sp-custo-cobertura-fotografica': [...globalKeywords, 'custo cobertura bodas de ouro', 'fotógrafo bodas de ouro preço', 'quanto custa ensaio bodas SP'],
  'quanto-custa-ensaio-pre-wedding-sp-2026': [...globalKeywords, 'preço ensaio pré-wedding SP', 'quanto custa pré-wedding São Paulo', 'ensaio casal preço SP'],
  'album-fotografico-casamento-formatos-precos-sp': [...globalKeywords, 'álbum fotográfico casamento preço', 'formatos álbum casamento SP', 'álbum ou digital casamento'],

  // ── SERVIÇO (19) ───────────────────────────────────────────────
  'ensaio-pre-casamento-fotografo': [...globalKeywords, 'ensaio pré-casamento SP', 'o que é pré-wedding', 'ensaio casal antes casamento'],
  'fotografo-casamento-drone-incluso': [...globalKeywords, 'fotógrafo casamento drone incluso', 'drone casamento pacote', 'imagens aéreas casamento SP'],

  'mini-wedding-sao-paulo-fotografia-cobertura': [...globalKeywords, 'mini wedding SP fotografia', 'cobertura mini wedding São Paulo', 'fotógrafo mini wedding SP'],
  'ensaio-pre-wedding-sao-paulo-guia-completo': [...globalKeywords, 'guia pré-wedding São Paulo', 'ensaio casal SP locações', 'pré-wedding dicas SP'],
  'pre-wedding-praia-litoral-sp-fotografo': [...globalKeywords, 'pré-wedding praia SP', 'ensaio casal litoral São Paulo', 'pré-wedding Guarujá Santos'],
  'como-se-preparar-ensaio-pre-wedding-looks-dicas': [...globalKeywords, 'como se preparar pré-wedding', 'looks ensaio casal', 'dicas pré-wedding roupa maquiagem'],
  'fotos-bodas-de-prata-sao-paulo-ensaio': [...globalKeywords, 'bodas de prata SP ensaio', 'fotógrafo 25 anos casamento', 'ensaio bodas de prata São Paulo'],
  'fotografo-mini-wedding-sp-pacote-casamento-intimo': [...globalKeywords, 'pacote mini wedding SP', 'fotógrafo casamento íntimo SP', 'mini wedding até 50 convidados'],
  'mini-wedding-ou-casamento-completo-melhores-fotos': [...globalKeywords, 'mini wedding vs casamento completo', 'melhores fotos mini wedding', 'qual casamento rende mais fotos'],
  'mini-wedding-em-casa-sp-fotografia': [...globalKeywords, 'mini wedding em casa SP', 'casamento em casa fotógrafo', 'fotografia casamento residencial SP'],
  'melhores-lugares-pre-wedding-sao-paulo': [...globalKeywords, 'melhores locações pré-wedding SP', 'onde fazer pré-wedding São Paulo', 'locações ensaio casal SP'],
  'pre-wedding-guaruja-litoral-sp': [...globalKeywords, 'pré-wedding Guarujá', 'ensaio casal litoral SP', 'fotógrafo pré-wedding praia'],
  'pre-wedding-urbano-sao-paulo-locacoes': [...globalKeywords, 'pré-wedding urbano SP', 'ensaio casal rua São Paulo', 'locações urbanas ensaio SP'],
  'pre-wedding-ou-ensaio-pos-casamento-sp': [...globalKeywords, 'pré-wedding vs pós-casamento', 'ensaio pós-casamento SP', 'qual ensaio fazer casamento'],
  'pre-wedding-jardim-botanico-sao-paulo': [...globalKeywords, 'pré-wedding Jardim Botânico SP', 'ensaio casal Jardim Botânico', 'fotógrafo ensaio Jardim Botânico'],
  'ensaio-casal-pos-casamento-sp-tendencia': [...globalKeywords, 'ensaio pós-casamento SP', 'trash the dress São Paulo', 'tendência ensaio pós-casamento'],
  'ensaio-gestante-sao-paulo-casamento-pre-wedding': [...globalKeywords, 'ensaio gestante SP', 'fotógrafo gestante São Paulo', 'ensaio maternidade casamento SP'],
  'drone-casamento-sp-licenca-anac-fotografia-aerea': [...globalKeywords, 'drone casamento licença ANAC', 'regulamentação drone casamento SP', 'fotografia aérea casamento autorização'],

  // ── GUIA (84) ──────────────────────────────────────────────────
  'preciso-fotografo-profissional-casamento': [...globalKeywords, 'preciso fotógrafo profissional casamento', 'vale a pena fotógrafo casamento', 'fotógrafo amador vs profissional'],
  'quantas-horas-fotografo-casamento': [...globalKeywords, 'quantas horas fotógrafo casamento', 'tempo cobertura casamento SP', 'duração cobertura fotográfica'],
  'como-escolher-fotografo-casamento-sao-paulo': [...globalKeywords, 'como escolher fotógrafo casamento', 'dicas contratar fotógrafo SP', 'critérios fotógrafo casamento'],
  'convidados-com-cameras-atrapalhando-fotografo': [...globalKeywords, 'convidados câmeras casamento', 'celular atrapalha fotógrafo casamento', 'regras fotos convidados'],
  'melhor-fotografo-casamento-sao-paulo': [...globalKeywords, 'melhor fotógrafo casamento SP', 'top fotógrafos casamento São Paulo', 'fotógrafo referência casamento SP'],
  'quando-contratar-fotografo-casamento': [...globalKeywords, 'quando contratar fotógrafo casamento', 'antecedência contratar fotógrafo', 'prazo reserva fotógrafo SP'],
  'como-encontrar-fotografo-casamento-instagram': [...globalKeywords, 'fotógrafo casamento Instagram', 'como achar fotógrafo no Instagram', 'avaliar fotógrafo redes sociais'],
  'fotografo-casamento-pouca-antecedencia': [...globalKeywords, 'fotógrafo casamento última hora', 'fotógrafo disponível urgente SP', 'contratar fotógrafo em cima da hora'],
  'fotografo-casamento-junior-vs-senior': [...globalKeywords, 'fotógrafo júnior vs sênior casamento', 'diferença fotógrafo experiente', 'nível experiência fotógrafo SP'],
  'preciso-segundo-fotografo-casamento': [...globalKeywords, 'segundo fotógrafo casamento', 'dois fotógrafos casamento vale', 'cobertura dupla casamento SP'],
  'avaliar-fotografo-casamento-portfolio': [...globalKeywords, 'avaliar portfólio fotógrafo casamento', 'como saber fotógrafo é bom', 'analisar trabalho fotógrafo SP'],
  'contrato-fotografo-casamento-o-que-incluir': [...globalKeywords, 'contrato fotógrafo casamento', 'cláusulas contrato fotografia', 'o que ter no contrato fotógrafo'],
  'quanto-tempo-receber-fotos-casamento': [...globalKeywords, 'prazo entrega fotos casamento', 'quanto tempo receber fotos', 'tempo edição fotos casamento SP'],
  'posso-usar-fotos-casamento-redes-sociais': [...globalKeywords, 'direitos fotos casamento redes sociais', 'posso publicar fotos casamento', 'uso fotos casamento Instagram'],
  'fotografo-casamento-reportagem-vs-posado': [...globalKeywords, 'fotografia espontânea vs posada casamento', 'estilo reportagem casamento', 'fotógrafo documental vs posado'],
  'como-preparar-convidados-fotos-casamento': [...globalKeywords, 'preparar convidados fotos casamento', 'fotos grupo casamento dicas', 'organizar fotos família casamento'],
  'fotografo-casamento-alta-resolucao-entrega': [...globalKeywords, 'resolução fotos casamento', 'fotos casamento alta resolução', 'formato entrega fotógrafo casamento'],
  'casamento-pequeno-preciso-fotografo-profissional': [...globalKeywords, 'fotógrafo casamento pequeno', 'preciso fotógrafo casamento 50 pessoas', 'casamento simples fotógrafo SP'],
  'quantas-fotos-receber-casamento': [...globalKeywords, 'quantas fotos casamento entrega', 'número fotos fotógrafo casamento', 'quantidade fotos cobertura casamento'],
  'fotografo-casamento-trabalha-noite': [...globalKeywords, 'fotógrafo casamento noite festa', 'fotografia festa casamento noturna', 'flash casamento noite SP'],
  'posso-escolher-fotos-fotografo-entrega': [...globalKeywords, 'escolher fotos fotógrafo casamento', 'curadoria fotos casamento', 'direito escolha fotos casamento'],
  'por-que-fotografo-casamento-custa-caro': [...globalKeywords, 'por que fotógrafo casamento caro', 'custo real fotógrafo casamento', 'justificativa preço fotógrafo'],
  'casamento-com-chuva-como-fotografo-trabalha': [...globalKeywords, 'casamento com chuva fotografia', 'fotógrafo chuva casamento', 'plano B chuva casamento SP'],
  'como-comunicar-preferencias-fotografo': [...globalKeywords, 'briefing fotógrafo casamento', 'comunicar preferências fotógrafo', 'lista desejos fotos casamento'],
  'fotografo-vs-videografo-casamento': [...globalKeywords, 'fotógrafo ou cinegrafista casamento', 'foto e vídeo casamento', 'contratar fotógrafo cinegrafista junto'],
  'fotografo-casamento-experiencia-internacional': [...globalKeywords, 'fotógrafo casamento experiência internacional', 'fotógrafo casamento exterior', 'destination photographer SP'],
  'o-que-mudaria-casamento-fotografia': [...globalKeywords, 'o que mudar casamento fotografia', 'lições noivos fotografia', 'arrependimento fotos casamento'],
  'fotografo-casamento-entrega-album-ou-pasta': [...globalKeywords, 'álbum ou pasta digital casamento', 'formato entrega fotógrafo', 'álbum físico vs digital casamento'],
  'como-avaliar-reviews-fotografo-casamento': [...globalKeywords, 'reviews fotógrafo casamento', 'depoimentos fotógrafo casamento', 'avaliar recomendações fotógrafo'],
  'casamento-civil-vs-religioso-diferenca-fotografia': [...globalKeywords, 'casamento civil vs religioso fotos', 'diferença fotografia civil religioso', 'cobertura casamento civil SP'],
  'por-que-fotografos-cobram-mais-sao-paulo': [...globalKeywords, 'fotógrafo casamento SP mais caro', 'preço fotógrafo capital vs interior', 'custo vida fotógrafo SP'],
  'renegociar-fotografo-apos-casamento': [...globalKeywords, 'renegociar fotógrafo após casamento', 'insatisfação fotógrafo casamento', 'direitos noivos fotografia'],
  'tendencias-fotografia-casamento': [...globalKeywords, 'tendências fotografia casamento 2025', 'estilos fotografia casamento', 'fotografia casamento tendência'],
  'pacote-impressoes-fotografo-casamento': [...globalKeywords, 'pacote impressões fotógrafo casamento', 'álbum impresso casamento SP', 'impressão fotos casamento'],
  'dia-da-noiva-sessao-fotos': [...globalKeywords, 'dia da noiva fotos', 'making of noiva fotografia', 'getting ready fotos casamento'],
  'fotos-casal-apos-casamento': [...globalKeywords, 'ensaio casal após casamento', 'fotos pós-casamento', 'sessão trash the dress SP'],
  'fotografo-bodas-de-ouro-50-anos-casamento': [...globalKeywords, 'fotógrafo bodas de ouro', 'ensaio 50 anos casamento', 'bodas de ouro fotografia SP'],
  'melhor-fotografo-casamento-brasil': [...globalKeywords, 'melhor fotógrafo casamento Brasil', 'top fotógrafos casamento BR', 'fotógrafo premiado casamento'],
  'roupa-para-fotografia-de-casamento': [...globalKeywords, 'roupa fotografia casamento', 'o que vestir casamento fotos', 'look noiva noivo ensaio'],
  'fotografo-pedido-de-casamento': [...globalKeywords, 'fotógrafo pedido casamento SP', 'fotógrafo surpresa pedido', 'registrar pedido casamento'],
  'fotografo-casamento-catolico': [...globalKeywords, 'fotógrafo casamento católico SP', 'fotografia cerimônia religiosa', 'regras fotografia igreja católica'],
  'fotografo-casamento-sao-paulo-como-escolher': [...globalKeywords, 'como escolher fotógrafo SP', 'dicas fotógrafo casamento São Paulo', 'critérios fotógrafo casamento SP'],
  'cobertura-completa-casamento-sao-paulo-o-que-incluso': [...globalKeywords, 'cobertura completa casamento SP', 'o que inclui cobertura fotográfica', 'pacote completo fotógrafo casamento'],
  'erros-contratar-fotografo-casamento-sp': [...globalKeywords, 'erros contratar fotógrafo casamento', 'erros comuns fotografia casamento', 'como não errar fotógrafo SP'],
  'fotografia-casamento-autoral-sao-paulo': [...globalKeywords, 'fotografia autoral casamento SP', 'estilo autoral fotógrafo casamento', 'fotógrafo artístico casamento SP'],
  'cobertura-casamento-dois-fotografos-sao-paulo': [...globalKeywords, 'dois fotógrafos casamento SP', 'cobertura dupla casamento', 'segundo fotógrafo quando contratar'],
  'fotografia-filmagem-casamento-sp-contratar-junto-separado': [...globalKeywords, 'foto e filmagem casamento junto', 'contratar fotógrafo cinegrafista SP', 'foto e vídeo casamento pacote'],

  'casamento-jardins-sp-saloes-fotografo': [...globalKeywords, 'casamento Jardins SP salões', 'melhores salões Jardins casamento', 'fotógrafo casamento Jardins SP'],

  'casamento-vila-madalena-sp-guia-fotografico': [...globalKeywords, 'casamento Vila Madalena SP', 'espaços casamento Vila Madalena', 'fotógrafo Vila Madalena SP'],


  'casamento-alto-pinheiros-sp-fotografo': [...globalKeywords, 'casamento Alto de Pinheiros SP', 'locações casamento Alto Pinheiros', 'fotógrafo Alto Pinheiros SP'],
  'fotografo-casamento-abc-paulista-santo-andre-sao-bernardo': [...globalKeywords, 'fotógrafo casamento ABC paulista', 'casamento ABCDM cobertura', 'fotógrafo Santo André SBC SCS'],
  'fotografo-casamento-alphaville-barueri-sp': [...globalKeywords, 'casamento Alphaville Barueri SP', 'espaços Alphaville casamento', 'fotógrafo Alphaville SP'],
  'fotografo-casamento-zona-sul-sp': [...globalKeywords, 'casamento Zona Sul SP', 'fotógrafo Zona Sul São Paulo', 'bairros casamento Zona Sul SP'],
  'casamento-civil-cartorio-sao-paulo-fotografo': [...globalKeywords, 'casamento civil cartório SP', 'fotógrafo casamento civil SP', 'fotos cartório casamento'],
  'fotografo-bodas-de-ouro-sao-paulo': [...globalKeywords, 'bodas de ouro São Paulo', 'fotógrafo bodas 50 anos SP', 'celebração bodas de ouro SP'],
  'fotografo-casamento-rustico-sao-paulo': [...globalKeywords, 'casamento rústico SP', 'fotógrafo casamento rústico São Paulo', 'espaços rústicos casamento SP'],
  'destination-wedding-sao-paulo-fotografo': [...globalKeywords, 'destination wedding SP', 'casamento destino São Paulo', 'fotógrafo destination wedding'],
  'fotografia-documental-casamento-o-que-e': [...globalKeywords, 'fotografia documental casamento', 'o que é documental casamento', 'estilo documental fotógrafo SP'],
  'same-day-edit-casamento-o-que-e-vale-a-pena': [...globalKeywords, 'same day edit casamento', 'vídeo mesmo dia casamento', 'edição mesmo dia casamento SP'],
  'quantas-fotos-recebo-casamento-sp': [...globalKeywords, 'quantas fotos recebo casamento SP', 'entrega fotos fotógrafo SP', 'número fotos cobertura SP'],
  'contrato-fotografo-casamento-sp-o-que-deve-ter': [...globalKeywords, 'contrato fotógrafo casamento SP', 'cláusulas contrato fotografia SP', 'acordo fotógrafo casamento'],
  'chuva-casamento-fotografo-como-lidar-sp': [...globalKeywords, 'chuva casamento fotógrafo SP', 'como lidar chuva casamento', 'fotografia chuva casamento SP'],
  'tendencias-fotografia-casamento-2026-sao-paulo': [...globalKeywords, 'tendências fotografia casamento 2026', 'tendências casamento SP 2026', 'estilos casamento alta 2026'],
  'melhores-meses-casar-sp-estacao-fotos': [...globalKeywords, 'melhores meses casar SP', 'melhor época casamento São Paulo', 'estação do ano casamento fotos'],
  'locacoes-casamento-sao-paulo-alta-2026': [...globalKeywords, 'locações casamento SP 2026', 'espaços casamento alta 2026', 'tendência espaços casamento SP'],
  'fotografia-casamento-civil-sp-fotos-inesqueciveis': [...globalKeywords, 'fotografia casamento civil SP', 'fotos casamento civil cartório', 'casamento civil fotos bonitas'],
  'direcao-casais-fotografia-casamento-noivos-timidos': [...globalKeywords, 'direção casais fotografia', 'noivos tímidos fotógrafo', 'como posar casamento dicas'],
  'making-of-casamento-fotografia-preparacao-noiva': [...globalKeywords, 'making of casamento fotos', 'fotografia preparação noiva', 'getting ready casamento SP'],
  'entrega-fotos-casamento-prazo-formato-sp': [...globalKeywords, 'entrega fotos casamento prazo', 'formato entrega fotógrafo SP', 'como receber fotos casamento'],
  'casamento-ao-ar-livre-sao-paulo-riscos-fotografia': [...globalKeywords, 'casamento ar livre SP riscos', 'fotografia casamento externo', 'plano B casamento ao ar livre'],
  'paletas-cores-decoracao-casamento-2026-estilo-fotografico': [...globalKeywords, 'paleta cores casamento 2026', 'decoração casamento tendência', 'estilo fotográfico decoração'],
  'fotografo-casamento-zona-oeste-grande-sao-paulo': [...globalKeywords, 'casamento Zona Oeste SP', 'fotógrafo Taboão Osasco Carapicuíba', 'casamento Grande São Paulo Oeste'],
  'fotografo-casamento-alto-tiete-grande-sao-paulo': [...globalKeywords, 'casamento Alto Tietê SP', 'fotógrafo Itaquaquecetuba Poá', 'casamento Grande São Paulo Leste'],
  'fotografo-casamento-regiao-mairipora-caieiras': [...globalKeywords, 'casamento região Mairiporã Caieiras', 'fotógrafo Franco da Rocha', 'casamento norte Grande SP'],
  'fotografo-casamento-serra-mantiqueira': [...globalKeywords, 'casamento Serra da Mantiqueira', 'fotógrafo casamento serra SP', 'Welucci Canto Verde serra'],
}
