export const globalKeywords = [
  'fotógrafo de casamento em São Paulo',
  'fotógrafo de casamento SP',
  'Ivan Dias fotógrafo',
]

export const pageKeywords: Record<string, string[]> = {
  home: [
    ...globalKeywords,
    'fotografia de casamento São Paulo',
    'pré-wedding São Paulo',
    'mini wedding São Paulo',
    'fotógrafo casamento Moema',
    'fotógrafo casamento Itaim Bibi',
    'fotógrafo casamento autoral SP',
  ],
  'cobertura-completa': [
    ...globalKeywords,
    'cobertura completa casamento SP',
    'fotógrafo making of noiva SP',
    'foto e vídeo casamento São Paulo',
    'fotógrafo cerimônia e festa SP',
  ],
  'pre-wedding': [
    ...globalKeywords,
    'ensaio pré-wedding São Paulo',
    'book de noivos SP',
    'ensaio externo casal São Paulo',
    'pré-wedding parques SP',
  ],
  'mini-wedding': [
    ...globalKeywords,
    'fotógrafo mini wedding São Paulo',
    'casamento intimista SP',
    'mini wedding até 80 convidados SP',
    'fotógrafo cerimônia pequena SP',
  ],
  drone: [
    ...globalKeywords,
    'drone casamento São Paulo',
    'fotografia aérea casamento SP',
    'vídeo drone casamento SP',
    'fotógrafo com drone casamento',
  ],
  'itaim-bibi': [
    ...globalKeywords,
    'fotógrafo casamento Itaim Bibi',
    'fotógrafo casamento Itaim Bibi SP',
    'ensaio pré-wedding Itaim Bibi',
    'mini wedding Itaim Bibi',
  ],
  jardins: [
    ...globalKeywords,
    'fotógrafo casamento Jardins SP',
    'fotógrafo casamento Jardim Paulista',
    'ensaio pré-wedding Jardins',
  ],
  moema: [
    ...globalKeywords,
    'fotógrafo casamento Moema',
    'fotógrafo casamento Moema SP',
    'ensaio casal Moema',
    'mini wedding Moema',
  ],
  pinheiros: [
    ...globalKeywords,
    'fotógrafo casamento Pinheiros SP',
    'casamento industrial Pinheiros',
    'ensaio pré-wedding Pinheiros',
  ],
  'vila-mariana': [
    ...globalKeywords,
    'fotógrafo casamento Vila Mariana',
    'fotógrafo casamento Vila Mariana SP',
    'casamento igreja Vila Mariana',
  ],
  perdizes: [
    ...globalKeywords,
    'fotógrafo casamento Perdizes SP',
    'casamento Perdizes São Paulo',
    'ensaio pré-wedding Perdizes',
  ],
  tatuape: [
    ...globalKeywords,
    'fotógrafo casamento Tatuapé',
    'fotógrafo casamento Zona Leste SP',
    'casamento Tatuapé fotógrafo',
  ],
  santana: [
    ...globalKeywords,
    'fotógrafo casamento Santana SP',
    'fotógrafo casamento Zona Norte SP',
    'casamento Santana São Paulo',
  ],
  'santo-andre': [
    ...globalKeywords,
    'fotógrafo de casamento Santo André',
    'fotógrafo casamento ABC paulista',
    'fotógrafo casamento Santo André SP',
    'ensaio pré-wedding Santo André',
    'mini wedding Santo André',
    'fotógrafo casamento ABCD',
  ],
  'sao-bernardo': [
    ...globalKeywords,
    'fotógrafo de casamento São Bernardo do Campo',
    'fotógrafo casamento SBC',
    'fotógrafo sítio são jorge',
    'fotógrafo napoleão buffet',
    'casamento São Bernardo do Campo fotógrafo',
    'fotógrafo ABC paulista casamento',
  ],
  'sao-caetano': [
    ...globalKeywords,
    'fotógrafo de casamento São Caetano do Sul',
    'fotógrafo casamento São Caetano SP',
    'mini wedding São Caetano do Sul',
    'casamento intimista São Caetano',
  ],
}
